= Cadro

New DRO software for TouchDRO(-like) hardware.

== Why?

For the most part, the concepts of how the DRO interface works was set in
neon tubes in the 50s.  It was designed around two coordinate spaces that
could fit inside wire-wrapped RAM and named ABS and INC (in the early days
of software development, letters were quite expensive).

These two reference positions were neither absolute, nor incremental,
except sometimes by convention, but then not even really.  For example,
you never actually see the absolute coordinate of the scale except possibly
on first power-on, and then you "set" the absolute coordiante to be some
place in your reference space.

Now that we are using an Android tablet (or maybe I'll support iPads too),
we have RAM so large, we can fit millions of Commodore 64 programs in it.

=== Destructive Actions

TouchDRO's philosophy of warning on destructive actions like zeroing doesn't
help my ADHD-adled brain much.  I usually just power through those... or even
sometimes I carefully reason and then find out I'm wrong.

CaDRO's philosophy is _anything can be undone_, including zeroing.

===


== Development

Start the nREPLs and build everything for debug.

----
$ npm install
$ npx shadow-cljs watch app
----

Connect to the CLJS REPL:

----
$ npx shadow-cljs cljs-repl app
----

Run tests:

[source,clojure]
----
$ npx shadow-cljs watch test
----

Testing on tablet:

----
$ npx shadow-cljs release app
$ adb shell pm clear net.eraserhead.cadro # Clear application state
$ npx cap run android
----

== Running droserve (fake DRO server)

=== Pairing the Tablet

----
$ bluetoothctl
> discoverable on 
----

In a separate terminal:

----
$ droserve
----

Attempt to pair the tablet in Settings | Bluetooth.

You might have to type "yes" to allow the connection in bluetoothctl.  Then in bluetoothctl:

----
> devices Paired
Device 78:D6:DC:C1:BA:22 Lenovo Tab M10 Plus 3rd Gen
> trust 78:D6:DC:C1:BA:22
----

This prevents needing to allow the connection every time.

From this point forward, just `droserve` should be necessary.

== Resources

* https://github.com/Aggebitter/TouchDRO-Simulator-on-ESP32[TouchDRO-Simulator-on-ESP32]
